export const GET_JOBADS_START = 'GET_JOBADS_START'
export const GET_JOBADS_SUCCESS = 'GET_JOBADS_SUCCESS'
export const GET_JOBADS_ERROR = 'GET_JOBADS_ERROR'

export const GET_JOBAD_START = 'GET_JOBAD_START'
export const GET_JOBAD_SUCCESS = 'GET_JOBAD_SUCCESS'
export const GET_JOBAD_ERROR = 'GET_JOBAD_ERROR'